Feat: kafka to postgresql
united-manufacturing-hub/Sarama-Kafka-Wrapper pull request #3
Opened 2023-05-10 13:53 UTC by Ayato77

### Description
- Option for AutoCommit.Enable
- Export Client.Producer and Clien.Consumer
- Client.saramaClient is added to create OffsetManager
- New methods for OffsetManager

2023-05-10 14:08 UTC, Scarjit requested changes

2023-05-10 14:08 UTC, Scarjit commented on pkg/kafka/client.go
> +	client.saramaClient, err = sarama.NewClient(opts.Brokers, config)
Replace with 
config.Consumer.Offsets.AutoCommit.Enable = opts.AutoCommit

2023-05-10 14:08 UTC, Scarjit commented on pkg/kafka/client.go
> +func (c *Client) CreateOffsetManager(consumerName string) (sarama.OffsetManager, error) {
c.saramaClient with c.consumer

2023-05-10 14:08 UTC, Scarjit commented on pkg/kafka/client.go
> +func (c *Client) GetAutoCommitEnableStatus() bool {
c.saramaClient with c.consumer

2023-05-11 09:11 UTC, Ayato77 commented on pkg/kafka/client.go
> +	client.saramaClient, err = sarama.NewClient(opts.Brokers, config)
Replaced.

2023-05-12 09:23 UTC, Scarjit approved these changes

2023-05-12 09:23 UTC, merged